title: How to make great mash
author: Artemaesia
email: potatotential@mash.com
description: > # this means to ignore newlines until "baseurl:"
  Making mash need not necessarily be hard, here's a few quick steps to get you started:
*Ingredients:
  -Russet potatoes
  -butter
  -salt
  -water
*Steps:
  -Boil potatoes 

# social links
twitter_username: @potates
github_username:  Artemaesia

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
